apiVersion: v1
kind: Service
metadata:
  name: okps-collector
  namespace: okps
  labels:
    app.kubernetes.io/name: okps-collector
    app.kubernetes.io/component: collector
    app.kubernetes.io/part-of: okps-pipeline
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: okps-collector
  ports:
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: otlp-grpc
