apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: okps-consumer
  namespace: okps
  labels:
    app.kubernetes.io/name: okps-consumer
    app.kubernetes.io/component: consumer
    app.kubernetes.io/part-of: okps-pipeline
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: okps-consumer
  minReplicas: 2
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
