apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: okps-producer
  namespace: okps
  labels:
    app.kubernetes.io/name: okps-producer
    app.kubernetes.io/component: producer
    app.kubernetes.io/part-of: okps-pipeline
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: okps-producer
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
