package producer

import "github.com/prometheus/client_golang/prometheus"

// Metrics bundles producer counters required by the user story.
type Metrics struct {
	MessagesSent   prometheus.Counter
	SendErrors     prometheus.Counter
	PayloadBytes   prometheus.Counter
	registererUsed prometheus.Registerer
}

func NewMetrics(reg prometheus.Registerer) (*Metrics, error) {
	if reg == nil {
		reg = prometheus.DefaultRegisterer
	}

	m := &Metrics{
		MessagesSent: prometheus.NewCounter(prometheus.CounterOpts{
			Name: "okps_producer_messages_sent_total",
			Help: "Total number of producer messages sent successfully.",
		}),
		SendErrors: prometheus.NewCounter(prometheus.CounterOpts{
			Name: "okps_producer_send_errors_total",
			Help: "Total number of producer send/export errors.",
		}),
		PayloadBytes: prometheus.NewCounter(prometheus.CounterOpts{
			Name: "okps_producer_payload_bytes_total",
			Help: "Total original payload bytes generated by producer.",
		}),
		registererUsed: reg,
	}

	if err := reg.Register(m.MessagesSent); err != nil {
		return nil, err
	}
	if err := reg.Register(m.SendErrors); err != nil {
		return nil, err
	}
	if err := reg.Register(m.PayloadBytes); err != nil {
		return nil, err
	}

	return m, nil
}
